server:
  port: 8098    #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://172.23.239.60:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: user   #current service name to be used by the eureka server

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    com.stackroute: DEBUG